/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examen1dad;

/**
 *
 * @author 2damb
 */
public class JDialogAviso extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAviso
     */
    String mensaje;
    public JDialogAviso(java.awt.Frame parent, boolean modal, String mensaje) {
        super(parent, modal);
        this.mensaje = mensaje;
        initComponents();
        jLabelAviso.setText(mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 100));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabelAviso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAviso.setText("Popup emergente");
        getContentPane().add(jLabelAviso);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAviso;
    // End of variables declaration//GEN-END:variables
}
